export const CompanyList = [
    {
      companyName: "CloudWalk Digital Inc.",
      ratings: "0.0",
      reviews: "0",
      tags: ["Web Development", "Mobile App Development"],
      sales: null,
      time: null,
      employees: "50-249",
      location: "Quezon City",
      companyPic: null,
    },
    {
      companyName: "White Widget",
      ratings: "4.6",
      reviews: "6",
      tags: ["Web Development", "Mobile App Development"],
      sales: null,
      time: null,
      employees: "50-249",
      location: "Quezon City",
      companyPic: null,
    },
    {
        companyName: "Sterling International Computing",
        ratings: "4.6",
        reviews: "6",
        tags: ["Web Development", "Mobile App Development"],
        sales: null,
        time: null,
        employees: "50-249",
        location: "Quezon City",
        companyPic: null,
      },
      {
        companyName: "White Widget",
        ratings: "4.6",
        reviews: "6",
        tags: ["Web Development", "Mobile App Development"],
        sales: null,
        time: null,
        employees: "50-249",
        location: "Quezon City",
        companyPic: null,
      },
      {
        companyName: "White Widget",
        ratings: "4.6",
        reviews: "6",
        tags: ["Web Development", "Mobile App Development"],
        sales: null,
        time: null,
        employees: "50-249",
        location: "Quezon City",
        companyPic: null,
      },
      {
        companyName: "White Widget",
        ratings: "4.6",
        reviews: "6",
        tags: ["Web Development", "Mobile App Development"],
        sales: null,
        time: null,
        employees: "50-249",
        location: "Quezon City",
        companyPic: null,
      },
  ];
  