export const IndustryList = [
    "Mobile Apps Development",
    "Software Development",
    "Web Development",
    "Emerging Tech Development",
    "Frameworks Development",
    "E-Commerce Development",
    "Consulting",
    "Cloud",
    "IT Support",
    "Security",
    "Digital Marketing",
    "Advertising",
    "Branding",
    "Communication Strategy",
    "Video Production",
    "Animation",
    "Websites Design",
    "Design Concepts",
    "Full Service",
    "Sales Support",
    "Call Center Services",
    "Financial Services",
    "Admin Support",
    "Human Resources"
]