export const ServicesList = [
  "Mobile App Development",
  "Software Development",
  "Web Development",
  "Artificial Intelligence",
  "Blockchain",
  'AR/VR',
  'IoT',
  'React Native',
  'Flutter',
  'DOTNET',
  'Ruby on Rails',
  'Java',
  'E-Commerce',
  'BigCommerce',
  'WooCommerce',
  'Systems Integration Consulting',
  'ERP',
  'Cloud Consulting',
  'IT Services',
  'Cybersecurity',
  'Digital Marketing',
  'SEO',
  'Social Media Marketing',
  'Email Marketing',
  'Content Marketing',
  'Advertising',
  'Pay Per Click',
  'Media Buying & Planning',
  'Branding',
  'Public Relations',
  'Market Research',
  'Digital Strategy',
  'Video Production',
  'Commercials',
  'Corporate Videos',
  '2D Animation',
  '3D Animation',
  'Motion Graphics',
  'Web Design',
  'User Experience',
  'Logo Design',
  'Graphic Design',
  'Product Design',
  'Packaging Design',
  'Digital Design',
  'Sales Outsourcing',
  'Customer Support',
  'Lead Generation',
  'Lead Qualification',
  'BPO',
  'Call Center',
  'Answering Services',
  'Outbound Call Centers',
  'Accounting',
  'Private Equity',
  'Payroll Processing',
  'Mergers & Acquisitions',
  'Wealth & Asset Management',
  'Appointment Setting',
  'Virtual Receptionist',
  'Virtual Assistant',
  'Data Entry',
  'HR Recruiting',
  'HR Staffing',
  'Executive Search'
];
